[package]
name = "basic"
version = "0.1.0"
authors = ["Jonathan Fok kan <jfokkan@gmail.com>"]

[dependencies]
iron = "*"
router = "*"

iron-postgres-middleware = { git = "https://github.com/jonfk/iron-postgres-middleware.git" }